//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IO.Ably.CustomSerialisers {

#pragma warning disable SA1600 // Elements should be documented
#pragma warning disable CS1591 // Missing XML comment for publicly visible type or member
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public class System_Net_HttpStatusCodeSerializer : MsgPack.Serialization.EnumMessagePackSerializer<System.Net.HttpStatusCode> {
        
        public System_Net_HttpStatusCodeSerializer(MsgPack.Serialization.SerializationContext context) : 
                this(context, MsgPack.Serialization.EnumSerializationMethod.ByName) {
        }
        
        public System_Net_HttpStatusCodeSerializer(MsgPack.Serialization.SerializationContext context, MsgPack.Serialization.EnumSerializationMethod enumSerializationMethod) : 
                base(context, enumSerializationMethod) {
        }
        
        protected override void PackUnderlyingValueTo(MsgPack.Packer packer, System.Net.HttpStatusCode enumValue) {
            packer.Pack(((int)(enumValue)));
        }
        
        protected override System.Net.HttpStatusCode UnpackFromUnderlyingValue(MsgPack.MessagePackObject messagePackObject) {
            return ((System.Net.HttpStatusCode)(messagePackObject.AsInt32()));
        }
        
        private static T @__Conditional<T>(bool condition, T whenTrue, T whenFalse)
         {
            if (condition) {
                return whenTrue;
            }
            else {
                return whenFalse;
            }
        }
    }
#pragma warning restore SA1600 // Elements should be documented
#pragma warning restore CS1591 // Missing XML comment for publicly visible type or member
}
