/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

namespace Ably.Protocol
{
    internal enum TAction
    {
        HEARTBEAT = 0,
        ACK = 1,
        NACK = 2,
        CONNECT = 3,
        CONNECTED = 4,
        DISCONNECT = 5,
        DISCONNECTED = 6,
        CLOSE = 7,
        CLOSED = 8,
        ERROR = 9,
        ATTACH = 10,
        ATTACHED = 11,
        DETACH = 12,
        DETACHED = 13,
        PRESENCE = 14,
        MESSAGE = 15,
    }
}
