/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using System.Threading.Tasks;
using Thrift;
using Thrift.Collections;
using System.Runtime.Serialization;
using Thrift.Protocol;
using Thrift.Transport;

namespace Ably.Protocol
{

#if !SILVERLIGHT
    [Serializable]
#endif
    public partial class TMessageBundle : TBase
    {
        private List<TProtocolMessage> _items;

        public List<TProtocolMessage> Items
        {
            get
            {
                return _items;
            }
            set
            {
                __isset.items = true;
                this._items = value;
            }
        }


        public Isset __isset;
#if !SILVERLIGHT
        [Serializable]
#endif
        public struct Isset
        {
            public bool items;
        }

        public TMessageBundle()
        {
        }

        public void Read(TProtocol iprot)
        {
            TField field;
            iprot.ReadStructBegin();
            while (true)
            {
                field = iprot.ReadFieldBegin();
                if (field.Type == Thrift.Protocol.TType.Stop)
                {
                    break;
                }
                switch (field.ID)
                {
                    case 1:
                        if (field.Type == Thrift.Protocol.TType.List)
                        {
                            {
                                Items = new List<TProtocolMessage>();
                                TList _list20 = iprot.ReadListBegin();
                                for (int _i21 = 0; _i21 < _list20.Count; ++_i21)
                                {
                                    TProtocolMessage _elem22 = new TProtocolMessage();
                                    _elem22 = new TProtocolMessage();
                                    _elem22.Read(iprot);
                                    Items.Add(_elem22);
                                }
                                iprot.ReadListEnd();
                            }
                        }
                        else
                        {
                            TProtocolUtil.Skip(iprot, field.Type);
                        }
                        break;
                    default:
                        TProtocolUtil.Skip(iprot, field.Type);
                        break;
                }
                iprot.ReadFieldEnd();
            }
            iprot.ReadStructEnd();
        }

        public void Write(TProtocol oprot)
        {
            TStruct struc = new TStruct("TMessageBundle");
            oprot.WriteStructBegin(struc);
            TField field = new TField();
            if (Items != null && __isset.items)
            {
                field.Name = "items";
                field.Type = Thrift.Protocol.TType.List;
                field.ID = 1;
                oprot.WriteFieldBegin(field);
                {
                    oprot.WriteListBegin(new TList(Thrift.Protocol.TType.Struct, Items.Count));
                    foreach (TProtocolMessage _iter23 in Items)
                    {
                        _iter23.Write(oprot);
                    }
                    oprot.WriteListEnd();
                }
                oprot.WriteFieldEnd();
            }
            oprot.WriteFieldStop();
            oprot.WriteStructEnd();
        }

        public override string ToString()
        {
            StringBuilder sb = new StringBuilder("TMessageBundle(");
            sb.Append("Items: ");
            sb.Append(Items);
            sb.Append(")");
            return sb.ToString();
        }

    }

}
