/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

namespace Ably.Protocol
{
    public enum TPresenceState
    {
        ENTER = 0,
        LEAVE = 1,
        UPDATE = 2,
    }
}
