//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IO.Ably.CustomSerialisers {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("MsgPack.Serialization.CodeDomSerializers.CodeDomSerializerBuilder", "0.6.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public class IO_Ably_RequestCountSerializer : MsgPack.Serialization.MessagePackSerializer<IO.Ably.RequestCount> {
        
        private MsgPack.Serialization.MessagePackSerializer<string> _serializer0;
        
        private MsgPack.Serialization.MessagePackSerializer<double> _serializer1;
        
        public IO_Ably_RequestCountSerializer(MsgPack.Serialization.SerializationContext context) : 
                base(context) {
            MsgPack.Serialization.PolymorphismSchema schema0 = default(MsgPack.Serialization.PolymorphismSchema);
            schema0 = null;
            this._serializer0 = context.GetSerializer<string>(schema0);
            MsgPack.Serialization.PolymorphismSchema schema1 = default(MsgPack.Serialization.PolymorphismSchema);
            schema1 = null;
            this._serializer1 = context.GetSerializer<double>(schema1);
        }
        
        protected override void PackToCore(MsgPack.Packer packer, IO.Ably.RequestCount objectTree) {
            packer.PackMapHeader(3);
            this._serializer0.PackTo(packer, "Failed");
            this._serializer1.PackTo(packer, objectTree.Failed);
            this._serializer0.PackTo(packer, "Refused");
            this._serializer1.PackTo(packer, objectTree.Refused);
            this._serializer0.PackTo(packer, "Succeeded");
            this._serializer1.PackTo(packer, objectTree.Succeeded);
        }
        
        protected override IO.Ably.RequestCount UnpackFromCore(MsgPack.Unpacker unpacker) {
            IO.Ably.RequestCount result = default(IO.Ably.RequestCount);
            result = new IO.Ably.RequestCount();
            if (unpacker.IsArrayHeader) {
                int unpacked = default(int);
                int itemsCount = default(int);
                itemsCount = MsgPack.Serialization.UnpackHelpers.GetItemsCount(unpacker);
                System.Nullable<double> nullable = default(System.Nullable<double>);
                if ((unpacked < itemsCount)) {
                    nullable = MsgPack.Serialization.UnpackHelpers.UnpackNullableDoubleValue(unpacker, typeof(IO.Ably.RequestCount), "Double Failed");
                }
                if (nullable.HasValue) {
                    result.Failed = nullable.Value;
                }
                unpacked = (unpacked + 1);
                System.Nullable<double> nullable0 = default(System.Nullable<double>);
                if ((unpacked < itemsCount)) {
                    nullable0 = MsgPack.Serialization.UnpackHelpers.UnpackNullableDoubleValue(unpacker, typeof(IO.Ably.RequestCount), "Double Refused");
                }
                if (nullable0.HasValue) {
                    result.Refused = nullable0.Value;
                }
                unpacked = (unpacked + 1);
                System.Nullable<double> nullable1 = default(System.Nullable<double>);
                if ((unpacked < itemsCount)) {
                    nullable1 = MsgPack.Serialization.UnpackHelpers.UnpackNullableDoubleValue(unpacker, typeof(IO.Ably.RequestCount), "Double Succeeded");
                }
                if (nullable1.HasValue) {
                    result.Succeeded = nullable1.Value;
                }
                unpacked = (unpacked + 1);
            }
            else {
                int itemsCount0 = default(int);
                itemsCount0 = MsgPack.Serialization.UnpackHelpers.GetItemsCount(unpacker);
                for (int i = 0; (i < itemsCount0); i = (i + 1)) {
                    string key = default(string);
                    string nullable2 = default(string);
                    nullable2 = MsgPack.Serialization.UnpackHelpers.UnpackStringValue(unpacker, typeof(IO.Ably.RequestCount), "MemberName");
                    if (((nullable2 == null) 
                                == false)) {
                        key = nullable2;
                    }
                    else {
                        throw MsgPack.Serialization.SerializationExceptions.NewNullIsProhibited("MemberName");
                    }
                    if ((key == "Succeeded")) {
                        System.Nullable<double> nullable5 = default(System.Nullable<double>);
                        nullable5 = MsgPack.Serialization.UnpackHelpers.UnpackNullableDoubleValue(unpacker, typeof(IO.Ably.RequestCount), "Double Succeeded");
                        if (nullable5.HasValue) {
                            result.Succeeded = nullable5.Value;
                        }
                    }
                    else {
                        if ((key == "Refused")) {
                            System.Nullable<double> nullable4 = default(System.Nullable<double>);
                            nullable4 = MsgPack.Serialization.UnpackHelpers.UnpackNullableDoubleValue(unpacker, typeof(IO.Ably.RequestCount), "Double Refused");
                            if (nullable4.HasValue) {
                                result.Refused = nullable4.Value;
                            }
                        }
                        else {
                            if ((key == "Failed")) {
                                System.Nullable<double> nullable3 = default(System.Nullable<double>);
                                nullable3 = MsgPack.Serialization.UnpackHelpers.UnpackNullableDoubleValue(unpacker, typeof(IO.Ably.RequestCount), "Double Failed");
                                if (nullable3.HasValue) {
                                    result.Failed = nullable3.Value;
                                }
                            }
                            else {
                                unpacker.Skip();
                            }
                        }
                    }
                }
            }
            return result;
        }
        
        private static T @__Conditional<T>(bool condition, T whenTrue, T whenFalse)
         {
            if (condition) {
                return whenTrue;
            }
            else {
                return whenFalse;
            }
        }
    }
}
