// Auto-Generated by FAKE; do not edit
// <auto-generated/>
using System.Reflection;

[assembly: AssemblyCompany("Ably Realtime")]
[assembly: AssemblyDescription("Client for ably.io realtime service")]
[assembly: AssemblyProduct("Ably .Net Library")]
[assembly: AssemblyVersion("1.2.2")]
[assembly: AssemblyFileVersion("1.2.2")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const System.String AssemblyCompany = "Ably Realtime";
        internal const System.String AssemblyDescription = "Client for ably.io realtime service";
        internal const System.String AssemblyProduct = "Ably .Net Library";
        internal const System.String AssemblyVersion = "1.2.2";
        internal const System.String AssemblyFileVersion = "1.2.2";
    }
}
