// Auto-Generated by FAKE; do not edit
// <auto-generated/>
using System.Reflection;

[assembly: AssemblyCompany("Ably")]
[assembly: AssemblyProduct("Ably .NET Library")]
[assembly: AssemblyVersion("1.2.9")]
[assembly: AssemblyFileVersion("1.2.9")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const System.String AssemblyCompany = "Ably";
        internal const System.String AssemblyProduct = "Ably .NET Library";
        internal const System.String AssemblyVersion = "1.2.9";
        internal const System.String AssemblyFileVersion = "1.2.9";
    }
}
