name: Build and test
on: [ "push" ]


jobs:
  build-and-test-windows:

    runs-on: windows-latest
    env:
      DOTNET_NOLOGO: true

    strategy:
      matrix:
        target: [ "Test.NetStandard", "Test.NetFramework" ]

    steps:
      - uses: actions/checkout@v2
        with: 
          submodules: 'recursive'
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '3.1.x'
      - run: dotnet tool install fake-cli --tool-path .
      - run: ./build.cmd ${{target}}
          