name: "Xamarin Build: macOS"
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  check:
    runs-on: macos-latest
    env:
      DOTNET_NOLOGO: true

    steps:
      - uses: actions/checkout@v2
        with: 
          submodules: 'recursive'

      - name: Download dotnet framework
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: |
            3.1.x

      - name: Download dotnet build-script tools
        run:  dotnet tool restore
      
      #TODO - Need to refactor this step to restore packages using nuget restore, instead restore while building xamarin project
      - name: Install mono and restore packages
        run: |
          chmod +x ./tools/mono-install.sh
          ./tools/mono-install.sh
          nuget restore ./src/IO.Ably.Xamarin.sln

      - name: Build Xamarin projects
        run: ./build.sh Build.Xamarin
