name: "Integration Test: macOS"
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  check:
    runs-on: macos-latest
    env:
      DOTNET_NOLOGO: true

    steps:
      - uses: actions/checkout@v2
        with: 
          submodules: 'recursive'
      - name: Download dotnet framework
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: |
            3.1.x
            6.0.x
            7.0.x
      - name: Download fake-cli
        run:  dotnet tool install fake-cli --version 5.20.4 --tool-path .
      - name: Restore packages
        run: |
          nuget restore ./src/IO.Ably.Xamarin.sln
      - name: Build Xamarin projects
        run: ./build.sh Build.Xamarin
      - name: Unit tests
        run: ./build.sh Test.NetStandard.Unit.WithRetry
      - name: Integration tests
        run: ./build.sh Test.NetStandard.Integration
