name: "Unit and Integration Test: Linux"
on:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  check:
    runs-on: ubuntu-22.04
    env:
      DOTNET_NOLOGO: true

    strategy:
      fail-fast: false
      matrix:
        targetframework: [ "net6.0", "net7.0", "net8.0", "net9.0" ]

    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
        with:
          submodules: 'recursive'
          persist-credentials: false

      - name: Download dotnet framework
        uses: actions/setup-dotnet@67a3573c9a986a3f9c594539f4ab511d57bb3ce9 # v4.3.1
        with:
          dotnet-version: |
            6.0.428
            7.0.410
            8.0.404
            9.0.100

      - name: Download dotnet build-script tools
        run:  dotnet tool restore

      - name: Unit tests
        run: ./build.sh --target=Test.NetStandard.Unit.WithRetry --framework=${{ matrix.targetframework }}

      - name: Integration tests
        run: ./build.sh --target=Test.NetStandard.Integration.WithRetry --framework=${{ matrix.targetframework }}
