name: "Unit and Integration Test: macOS (Mono)"
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  check:
    runs-on: macos-14
    env:
      DOTNET_NOLOGO: true

    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
        with:
          submodules: 'recursive'
          persist-credentials: false

      - name: Download dotnet framework
        uses: actions/setup-dotnet@67a3573c9a986a3f9c594539f4ab511d57bb3ce9 # v4.3.1
        with:
          dotnet-version: |
            3.1.426
            7.0.410

      - name: Download dotnet build-script tools
        run:  dotnet tool restore
      
      - name: Install mono
        run: |
          ./tools/mono-install.sh

      - name: Run Unit tests using mono
        run: ./build.sh --target=Test.NetFramework.Unit.WithRetry

      - name: Run Integration tests using mono
        run: ./build.sh --target=Test.NetFramework.Integration.WithRetry
