name: Unity
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  testAllModes:
    name: Test in ${{ matrix.testMode }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        testMode:
          - playmode
          - editmode
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with: 
          submodules: 'recursive'

      - uses: actions/cache@v2
        with:
          path: Library
          key: Library-${{ hashFiles('Assets/**', 'Packages/**', 'ProjectSettings/**') }}
          restore-keys: |
            Library-

      - name: Run tests
        uses: game-ci/unity-test-runner@v2
        id: tests
      # Unity License Details as per https://game.ci/docs/github/activation 
        env:
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
          UNITY_SERIAL: ${{ secrets.UNITY_SERIAL }}
        with:
          projectPath: ./unity
          testMode: ${{ matrix.testMode }}
          artifactsPath: ${{ matrix.testMode }}-artifacts
          unityVersion: 2020.3.19f1
          checkName: ${{ matrix.testMode }} Test Results
          
      # Upload editmode/testmode XML artifacts
      - uses: actions/upload-artifact@v2
        if: always()
        with:
          name: Test results for ${{ matrix.testMode }}
          path: ${{ steps.tests.outputs.artifactsPath }} 

  extract_unity_package:
    name: Generate Ably Unity Package
    runs-on: ubuntu-latest
    steps:
      # Checkout
      - name: Checkout repository
        uses: actions/checkout@v2
        with: 
          submodules: 'recursive'
        
      - name: Extract unity package
        id: extract_unity_package
        uses: FrostBanditTeam/extract-unity-package-action@1
        with:
          # Specify the unity project path, relative to the repo root.
          unityProjectPath: './unity'
          # Set the directory to package, relative to the project.
          packagePath: 'Assets/Ably'
          outputPackagePath: './artifacts/ably.unitypackage'

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: AblyUnity
          path: ${{ steps.extract_unity_package.outputs.artifactsPath }}